Neos:
  Fusion:
    defaultContext:
      Detect.Browser: 'WebExcess\ClientSystemDetection\Eel\Helper\BrowserHelper'
      Detect.OS: 'WebExcess\ClientSystemDetection\Eel\Helper\OsHelper'
      Detect.Device: 'WebExcess\ClientSystemDetection\Eel\Helper\DeviceHelper'
